import { Inter } from "next/font/google";
import "./globals.css";
import NextUiProvide from "@/provider/NextUiProvide";
import { ChipsProvider } from "@/context/ChipsContext";
import { FormProvider } from "@/context/FormContext";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUiProvide >
          <FormProvider>
         
<ChipsProvider>

        {children}
</ChipsProvider>
</FormProvider>

        </NextUiProvide>

      
      <Script src="../path/to/flowbite/dist/flowbite.min.js"></Script>
      </body>
    </html>
  );
}
